### ISSUE TITLE
Dialog with input

### ISSUE THREAD

**Issue by HZSamir** [arjunkomath/react-native-material-dialogs#3]
Hello,
Would it be possible to display an input field inside this dialog?

Thank you.

**Comment by arjunkomath** [comment]
@Unforgiven-wanda This library is based upon on https://github.com/javiersantos/MaterialStyledDialogs, I'm not sure if its possible to implement a custom view inside the modal.

**Comment by HZSamir** [comment]
Thank you. I will investigate further and comment here for posterity if I stumble upon anything worth noting.
